[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=936
DialogFontName=MS Shell Dlg
DialogFontSize=8
WelcomeFontName=Microsoft YaHei
WelcomeFontSize=12
TitleFontName=Microsoft YaHei
TitleFontSize=29
CopyrightFontName=Arial
CopyrightFontSize=8

[Messages]
ButtonNext=下一步(&N) >
ButtonBack=< 上一步(&B)
ButtonInstall=安装(&I)
ButtonFinish=完成(&F)
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonNo=否(&N)
ButtonYesToAll=全是(&A)
ButtonNoToAll=全否(&O)
ButtonAbort=中止(&A)
ButtonRetry=重试(&R)
ButtonIgnore=忽略(&I)
ButtonBrowse=浏览(&B)...
WizardInstalling=正在安装
WizardFinished=已完成
WelcomeLabel1=欢迎使用 [name/ver] 安装向导
WelcomeLabel2=此向导将指导您完成 [name] 的安装。%n%n建议您在继续之前关闭所有其他应用程序。
LicenseLabel=请在继续之前阅读许可协议。
LicenseLabel3=请在继续之前阅读以下许可协议。您必须接受协议的条款才能继续安装。
LicenseAccepted=我接受协议(&A)
LicenseNotAccepted=我不接受协议(&D)
WizardSelectDir=选择目标位置
SelectDirDesc=[name] 将被安装在何处？
SelectDirLabel=选择 [name] 安装的文件夹，然后单击"下一步"。
DiskSpaceMBLabel=至少需要 [mb] MB 的可用空间。
DirExists=文件夹：%n%n%1%n%n已存在。是否要安装到该文件夹中？
DirDoesntExist=文件夹：%n%n%1%n%n不存在。是否要创建该文件夹？
WizardSelectTasks=选择附加任务
SelectTasksDesc=需要执行哪些附加任务？
SelectTasksLabel=选择在安装 [name] 时要执行的附加任务，然后单击"下一步"。
WizardReady=准备安装
ReadyLabel=安装程序现在准备开始将 [name] 安装到您的计算机中。
ReadyLabel2=单击"安装"以继续。如果要复查或更改设置，请单击"上一步"。
PreparingDesc=安装程序正在准备将 [name] 安装到您的计算机中。
InstallingLabel=正在安装 [name]，请稍候...
FinishedHeadingLabel=[name/ver] 安装完成
FinishedLabel=[name] 已成功安装到您的计算机中。
FinishedLabelNoIcons=[name] 已成功安装到您的计算机中。
ClickFinish=单击"完成"退出安装程序。
Run=运行 [name](&L)
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成。如果您现在退出，[name] 将不会被安装。%n%n您可以稍后再次运行安装程序来完成安装。%n%n要退出安装吗？
FileInUse=文件正被使用中：%n%n%1%n%n请单击"忽略"继续安装，或"中止"退出安装程序。
FileInUseRetry=请关闭所有运行中的程序，然后重试。
FileInUseIgnore=&I
StatusClosingApplications=正在关闭应用程序...
StatusRestartingApplications=正在重启应用程序...
StatusRollback=正在回滚更改...

[CustomMessages]
BeveledLabel=安装向导
BeveledLabelUninstall=卸载向导
UninstallProgram=卸载
Uninstalling=正在卸载...
UninstallAppTitle=卸载
UninstallAppFullTitle=卸载 %1
UninstallSuccess=%1 已成功从您的计算机中卸载。
UninstallNotFound=卸载失败。未找到卸载信息。
UninstallConfirm=您确定要完全删除 %1 及其所有组件吗？